### PR TITLE
Support theming

### PR DESCRIPTION
**Pull request by NikolayXHD**

### CODE REVIEW

**Comment by drewnoakes** [comment]
Looks fine. I'm sure you've thought of this, but I wanted to point out that a heavily themed (eg. dark mode) editor will need different syntax highlighting schemes too.

**Comment by NikolayXHD** [comment]
I did automatic lightness correction for editors it's in the main repository, I find it's too many settings in all these syntax highlighting schemes to be dealing with them manually.

https://github.com/gitextensions/gitextensions/pull/7213#issuecomment-540289372

**Review by gerhardol — APPROVED** [review]
Works fine
Obviously merged together with the main repo

**Comment by gerhardol** [comment]
I suggest this is merged now.
The only "Dark Theme" specific is an additional constructor in HighlightColor.cs, for current master this follows the Windows colors so it should improve "WindowsBlinds" true dark themes.

**Comment by NikolayXHD** [comment]
I have no objections

**Comment by RussKie** [comment]
go for it

**Comment by NikolayXHD** [comment]
> go for it

I don't have write access here :)

**Pull request merged**
