### PR TITLE
Remove warning of empty post build event

### PR DESCRIPTION
**Pull request by vbjay**
Prevent warning from empty build event.

### CODE REVIEW

**Comment by drewnoakes** [comment]
Just set up CI for this build. Going to close and re-open in the hope it triggers a build.

**Comment by drewnoakes** [comment]
It did run a build, but we need some config. I'll get that sorted then kick off a new build.

**Comment by drewnoakes** [comment]
Looks good. Can you make a PR in GE that bumps this submodule?

**Comment by vbjay** [comment]
Sure. It will have to be after work.

**Pull request merged**
